name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  progress_dialog: ^1.2.2
  flutter_facebook_login: 3.0.0
  http: 0.12.1
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  cached_network_image: ^2.1.0+1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
